### ISSUE TITLE
웹폰트 아이콘 대신 이미지로 대체

### ISSUE THREAD

**Issue by marnitto** [Snoin/snoin.com#54]
#53 에서 새로 논의한 사항을 정리합니다.

현재 쓰는 웹폰트 기반 아이콘은 스크린의 크기에 맞춰 깔끔하게 나오지만, 다양한 웹 브라우저가 지원하지 않는 문제(접근성 문제)가 있어 대체가 필요합니다. 이전 논의에서는 responsive하게 이미지를 제공해서 font icon을 대체할 수 있는지를 논의하는 데까지 발전했습니다.

**Comment by item4** [comment]
제 생각엔 중간 정도인 svg를 써도 될 것 같습니다.

참고자료
-----------
* [font icon vs svg](https://css-tricks.com/icon-fonts-vs-svg/)
* [svg icon 사용법](https://css-tricks.com/svg-sprites-use-better-icon-fonts/)

**Comment by sjkoon** [comment]
변환이 따로 필요한거 아닌가요?

**Comment by item4** [comment]
네. 찾아보니 변환이 필요한 것 같습니다.

변환이 쉬운지를 확인해보겠습니다.

**Comment by item4** [comment]
일단 변환본 만들어봤습니다. 용량은 432kb입니다.

**Comment by item4** [comment]
일단 좀 써봤는데요, 현재 느낌상으로는 font-awesome에 비해 너무 어렵습니다.

원인은.. 제 추측으로는 font-awesome과 사용 방법 자체가 다르고, CSS를 하나하나 다 만들어줘야 한다는 점인 것 같습니다.

예를 들어서 현재 사이트의 한 부분인 "웹 서비스" 부분의 지구본 아이콘 흉내를 내려면 css가 이렇게 필요합니다.

```scss
.web-svg {
  position: relative;
  display: inline-block;
  width: 2em * 4;
  height: 2em * 4;
  vertical-align: middle;

  svg {
    position: absolute;
    left: 0;

    &:first-child {
      width: 2em * 4;
      height: 2em * 4;

      fill: red;
    }

    &:last-child {
      width: 2em * 2;
      height: 2em * 2;
      left: 2em;
      top: 2em;
      fill: white;
    }
  }
}
```

예전 소스는 이렇구요.

```scss
span {
  @extend .fa-stack;
  @extend .fa-4x;

  > i {
    @extend .fa;

    &:first-child {
      @extend .fa-circle;
      @extend .fa-stack-2x;
      @extend .text-primary;
    }

    &:last-child {
      @extend .fa-stack-1x;
      @extend .fa-inverse;
    }
  }
}
span.web {
  > i:last-child {
    @extend .fa-globe;
  }
}
```

단순히 CSS 길이만 놓고 보자면 비슷해 보이는데, 사용성 측면에선 아직 연구가 필요해보입니다.
